### ISSUE TITLE
Support for bootstrap command.

### ISSUE THREAD

**Issue by sreerajkksd** [codejamninja/dotstow#12]
We should support the use of bootstrap command (or a script) that a user can run to set up the bootstrap environment.

- Bootstrap script can be anything (should be platform dependent)
- 'dotstow bootstrap' should clone the dotfiles directory, invoke the manual-install script 
- Later user can either run 'dotstow sync or pull' to update and get the latest changes.

**Comment by sreerajkksd** [comment]
I can work on this, once I know how to setup the dev environment.

**Comment by clayrisser** [comment]
```sh
git clone git@github.com:codejamninja/dotstow.git
yarn
yarn start
```

**Comment by sreerajkksd** [comment]
Thanks @codejamninja I added those instructions in https://github.com/codejamninja/dotstow/pull/11.

To discuss further on how to configure bootstrap, this is what I'm proposing.

- Command: `dotstow bootstrap --remote <dotfiles_github_url>`
- This would clone the dotfiles repository at `/home/user/.dotfiles`
- Will get the bootstrap commands from  REPO/platform/bootstrap.yml and invoke them sequentially.

bootstrap.yml can have the following structure:
```yaml
- cmd: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim                        
  message: Vim plug                                                                
- cmd: git clone -q --depth 1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  message: Setting up tmux tpm                                                                                                               
```

and bootstrap command would invoke them sequentially. We can ask confirmation from the user for security concerns.
If bootstrap.yml is present in global, it would execute platform/bootstrap.yml first followed by global/bootstrap.yml

Let me know if that sounds good to you ?
